services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: travari-lib
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-rollback-on-timeout=ON
      --innodb_log_file_size=1G
      --sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
      --innodb_buffer_pool_size=512M
      --innodb_ft_enable_stopword=OFF
      --local_infile=1
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uadmin", "-padmin" ]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - trevari-test

  redis:
    image: redis:7.2-alpine
    healthcheck:
      test: [ "CMD-SHELL","redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --auto-aof-rewrite-percentage 100
      --auto-aof-rewrite-min-size 64mb
      --databases 1
      --timeout 0
    volumes:
      - ./redis-data:/data
    restart: unless-stopped
    networks:
      - trevari-test

  app:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
       SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - trevari-test
volumes:
  mysql_data:

networks:
  trevari-test:
    driver: bridge